In [1]:
import pandas as pd
import numpy as np

In [8]:
data_japan=pd.read_csv('JapaneseDiet_sample_set.csv')

In [9]:
data_japan

batch          ID   C14:0   C15:0     C16:0  trans C16:1n-7  C16:1n-7  \
0        1         QC1  370475   93728  12970025            1999     98131   
1        1         QC2  275962   73494   8955258           82236     55105   
2        1  413502-001  170101   39899   8859735           16634     47890   
3        1  413502-002  220002   58037  12770090           60502    105211   
4        1  413502-003  328291   98513  11787761           60658     70760   
..     ...         ...     ...     ...       ...             ...       ...   
197      6  407813-024  258529   76957  13467398            3996     75379   
198      6  407813-025  431166  133550  19372059            6495    144758   
199      6  407813-026  446021  135635  18353095           14113    149306   
200      6         QC1  378698   96578  12932752            2004    100725   
201      6         QC2  264576   69611   8503929           77278     52718   

      C17:0    C18:0  trans C18:1n-9  ...  C20:2n-6  C20:3n-6  C20:4n-6,AA  \
0    150031  6636680            5310  ...     11279    170819      2193757   
1    105188  4599681            2495  ...      8836    149877      1624242   
2     72522  5358597            4605  ...      9555    112827      1904269   
3    113270  6836123            5504  ...     12600    130742      2123065   
4    134014  6867304            7622  ...     11032     96388      2531716   
..      ...      ...             ...  ...       ...       ...          ...   
197  131616  7826571            7059  ...     11373    147435      2603646   
198  199108  9519393            7379  ...     18733    258934      3286660   
199  217661  8247549           10660  ...     20702    143134      1664830   
200  151394  6571109            5624  ...     11710    171565      2179564   
201   99427  4366436            3175  ...      8511    143872      1542695   

      C22:0  C20:5n-3,EPA  C22:4n-6   C24:0  C24:1n-9  C22:5n-3,DPA  \
0    165202        155035    140419  110025     58045         87094   
1     66852        122326    111005   58117     30685         76436   
2    205884         41274    176319  204281     30399         56177   
3    239235        229187    141009  254764     42862         87039   
4    189095         69447    179781  229639     38090         55398   
..      ...           ...       ...     ...       ...           ...   
197  266772        136641    169629  248089     51430        124709   
198  352934        117453    295826  307784     58639        163448   
199  253477        589047     73691  162706     80784        194745   
200  163597        161697    144548  181142     59704         88861   
201   60804        120759    107516   83823     29557         89527   

     C22:6n-3,DHA  
0          336776  
1          221497  
2          217637  
3          300227  
4          251588  
..            ...  
197        366107  
198        331205  
199        568450  
200        333571  
201        212454  

[202 rows x 29 columns]

In [10]:
LOD={'C14:0':23953,
'C15:0':4879,
'C16:0':21972,
'trans C16:1n-7':708,
'C16:1n-7':3174,
'C17:0':6404,
'C18:0':13327,
'trans C18:1n-9':422,
'trans C18:1n-7':471,
'C18:1n-9':2179,
'C18:1n-7':642,
'trans C18:2n-6':1154,
'C18:2 n-6, LA':2588,
'C18:3 n-6, GLA':1741,
'C18:3 n-3, ALA':5608,
'C20:0':8926,
'C20:1n-9':545,
'C20:2n-6':735,
'C20:3n-6':1476,
'C20:4n-6,AA':1105,
'C22:0':3507,
'C20:5n-3,EPA':1044,
'C22:4n-6':3831,
'C24:0':2636,
'C24:1n-9':540,
'C22:5n-3,DPA':904,
'C22:6n-3,DHA':901
}

In [11]:
type_string=['ID']
for column in data_japan:
    for row in range (len(data_japan[column])):
        if column not in type_string:
            data_japan.loc[row,column]=int(data_japan.loc[row,column])
            if column != 'batch':
                if data_japan.loc[row,column] <LOD[column]:
                    data_japan.loc[row,column]=LOD[column]

In [12]:
column_no_standardlized=['ID','batch']
for column in data_japan:
    if column not in column_no_standardlized:
        data_japan[column]=(data_japan[column]-data_japan[column].mean())/(data_japan[column].std())

In [13]:
data_japan

batch          ID     C14:0     C15:0     C16:0  trans C16:1n-7  \
0        1         QC1  0.174280  0.371182  0.176737       -0.434212   
1        1         QC2 -0.259782 -0.154495 -0.567204        3.352001   
2        1  413502-001 -0.745960 -1.027290 -0.584905        0.256382   
3        1  413502-002 -0.516784 -0.556066  0.139689        2.326420   
4        1  413502-003 -0.019455  0.495496 -0.042338        2.333781   
..     ...         ...       ...       ...       ...             ...   
197      6  407813-024 -0.339845 -0.064526  0.268901       -0.339978   
198      6  407813-025  0.453011  1.405754  1.363041       -0.222055   
199      6  407813-026  0.521234  1.459922  1.174226        0.137422   
200      6         QC1  0.212045  0.445225  0.169830       -0.433976   
201      6         QC2 -0.312073 -0.255375 -0.650836        3.118043   

     C16:1n-7     C17:0     C18:0  trans C18:1n-9  ...  C20:2n-6  C20:3n-6  \
0   -0.003172  0.582887  0.170248       -0.158571  ...  0.196983  0.502687   
1   -0.757647 -0.258925 -0.584723       -0.864996  ... -0.289332  0.177281   
2   -0.884164 -0.872146 -0.303447       -0.335491  ... -0.146204 -0.398418   
3    0.120978 -0.107207  0.244167       -0.109886  ...  0.459948 -0.120047   
4   -0.483131  0.282209  0.255724        0.421626  ...  0.147814 -0.653855   
..        ...       ...       ...             ...  ...       ...       ...   
197 -0.402136  0.237193  0.611256        0.280341  ...  0.215696  0.139336   
198  0.814448  1.504182  1.238665        0.360645  ...  1.680812  1.871858   
199  0.894199  1.852467  0.767283        1.184013  ...  2.072771  0.072506   
200  0.042315  0.608474  0.145946       -0.079772  ...  0.282780  0.514279   
201 -0.799504 -0.367073 -0.671170       -0.694350  ... -0.354028  0.083973   

     C20:4n-6,AA     C22:0  C20:5n-3,EPA  C22:4n-6     C24:0  C24:1n-9  \
0       0.475369  0.275747      0.174458  0.283102 -0.332846  0.987945   
1      -0.278807 -0.806336     -0.141967 -0.201631 -0.918833 -0.229772   
2       0.092017  0.723346     -0.926059  0.874721  0.731207 -0.242502   
3       0.381755  1.090286      0.891800  0.292825  1.301108  0.312192   
4       0.922908  0.538627     -0.653515  0.931773  1.017473  0.099803   
..           ...       ...           ...       ...       ...       ...   
197     1.018161  1.393258     -0.003484  0.764472  1.225754  0.693530   
198     1.922637  2.341244     -0.189108  2.844154  1.899649  1.014382   
199    -0.225059  1.246981      4.373065 -0.816552  0.261869  1.999994   
200     0.456574  0.258088      0.238906  0.351146  0.469992  1.061782   
201    -0.386795 -0.872878     -0.157126 -0.259128 -0.628639 -0.279977   

     C22:5n-3,DPA  C22:6n-3,DHA  
0        0.521153      0.601557  
1        0.203221     -0.373067  
2       -0.401112     -0.405702  
3        0.519512      0.292554  
4       -0.424350     -0.118663  
..            ...           ...  
197      1.643221      0.849536  
198      2.798819      0.554457  
199      3.732419      2.560242  
200      0.573863      0.574461  
201      0.593730     -0.449521  

[202 rows x 29 columns]

In [14]:
data_rpca=data_japan.drop(columns=['batch','ID'])

In [15]:
data_rpca

C14:0     C15:0     C16:0  trans C16:1n-7  C16:1n-7     C17:0  \
0    0.174280  0.371182  0.176737       -0.434212 -0.003172  0.582887   
1   -0.259782 -0.154495 -0.567204        3.352001 -0.757647 -0.258925   
2   -0.745960 -1.027290 -0.584905        0.256382 -0.884164 -0.872146   
3   -0.516784 -0.556066  0.139689        2.326420  0.120978 -0.107207   
4   -0.019455  0.495496 -0.042338        2.333781 -0.483131  0.282209   
..        ...       ...       ...             ...       ...       ...   
197 -0.339845 -0.064526  0.268901       -0.339978 -0.402136  0.237193   
198  0.453011  1.405754  1.363041       -0.222055  0.814448  1.504182   
199  0.521234  1.459922  1.174226        0.137422  0.894199  1.852467   
200  0.212045  0.445225  0.169830       -0.433976  0.042315  0.608474   
201 -0.312073 -0.255375 -0.650836        3.118043 -0.799504 -0.367073   

        C18:0  trans C18:1n-9  trans C18:1n-7  C18:1n-9  ...  C20:2n-6  \
0    0.170248       -0.158571       -0.047156  0.800893  ...  0.196983   
1   -0.584723       -0.864996       -0.118060  0.004011  ... -0.289332   
2   -0.303447       -0.335491       -0.400240 -0.493799  ... -0.146204   
3    0.244167       -0.109886       -0.142293  0.716618  ...  0.459948   
4    0.255724        0.421626        1.574839  0.060908  ...  0.147814   
..        ...             ...             ...       ...  ...       ...   
197  0.611256        0.280341       -0.150730 -0.116108  ...  0.215696   
198  1.238665        0.360645        1.613432  1.503042  ...  1.680812   
199  0.767283        1.184013       -0.482632  0.463648  ...  2.072771   
200  0.145946       -0.079772        0.019619  0.774618  ...  0.282780   
201 -0.671170       -0.694350       -0.075338 -0.095934  ... -0.354028   

     C20:3n-6  C20:4n-6,AA     C22:0  C20:5n-3,EPA  C22:4n-6     C24:0  \
0    0.502687     0.475369  0.275747      0.174458  0.283102 -0.332846   
1    0.177281    -0.278807 -0.806336     -0.141967 -0.201631 -0.918833   
2   -0.398418     0.092017  0.723346     -0.926059  0.874721  0.731207   
3   -0.120047     0.381755  1.090286      0.891800  0.292825  1.301108   
4   -0.653855     0.922908  0.538627     -0.653515  0.931773  1.017473   
..        ...          ...       ...           ...       ...       ...   
197  0.139336     1.018161  1.393258     -0.003484  0.764472  1.225754   
198  1.871858     1.922637  2.341244     -0.189108  2.844154  1.899649   
199  0.072506    -0.225059  1.246981      4.373065 -0.816552  0.261869   
200  0.514279     0.456574  0.258088      0.238906  0.351146  0.469992   
201  0.083973    -0.386795 -0.872878     -0.157126 -0.259128 -0.628639   

     C24:1n-9  C22:5n-3,DPA  C22:6n-3,DHA  
0    0.987945      0.521153      0.601557  
1   -0.229772      0.203221     -0.373067  
2   -0.242502     -0.401112     -0.405702  
3    0.312192      0.519512      0.292554  
4    0.099803     -0.424350     -0.118663  
..        ...           ...           ...  
197  0.693530      1.643221      0.849536  
198  1.014382      2.798819      0.554457  
199  1.999994      3.732419      2.560242  
200  1.061782      0.573863      0.574461  
201 -0.279977      0.593730     -0.449521  

[202 rows x 27 columns]

In [16]:
data=pd.read_csv('Trajan Data.csv')
data=data.drop(columns=['ID'])
data

C14:0     C15:0     C16:0  C16:1n-7     C17:0     C18:0  C18:1n-9  \
0   -2.093801 -2.723541 -0.377086 -2.644262 -2.464037 -0.595456 -1.325837   
1   -2.123295 -2.702019 -0.359527 -2.443661 -2.411606 -0.630911 -1.237108   
2   -1.944468 -2.467236 -0.389296 -2.610943 -2.333579 -0.623942 -1.341521   
3   -1.916122 -2.465344 -0.332935 -2.256630 -2.334859 -0.669889 -1.327932   
4   -1.992234 -2.600705 -0.372532 -2.479013 -2.338260 -0.593610 -1.324772   
..        ...       ...       ...       ...       ...       ...       ...   
302 -1.548106 -2.447905 -0.338117 -2.168738 -2.379843 -0.710505 -1.248606   
303 -1.674072 -2.161952 -0.378664 -2.368403 -2.232416 -0.644736 -1.261684   
304 -1.456173 -2.218745 -0.365639 -2.291914 -2.152106 -0.648770 -1.254247   
305 -1.965409 -2.449890 -0.380615 -2.513394 -2.349032 -0.652703 -1.195881   
306 -1.910333 -2.402002 -0.402791 -2.606874 -2.242061 -0.630265 -1.334232   

     C18:1n-7  C18:2 n-6, LA  C18:3 n-6, GLA  ...  C20:2n-6  C20:3 n-6  \
0   -2.438840      -0.963960       -3.383672  ... -3.344289  -2.272093   
1   -2.447868      -0.946731       -3.113747  ... -3.365357  -2.349307   
2   -2.576118      -0.874269       -3.340659  ... -3.418058  -2.476705   
3   -2.354594      -0.947182       -2.974628  ... -3.366926  -2.135205   
4   -2.393527      -1.038752       -3.096222  ... -3.339581  -2.127855   
..        ...            ...             ...  ...       ...        ...   
302 -2.406842      -0.980861       -2.667025  ... -3.270021  -1.837632   
303 -2.505322      -0.986398       -2.852641  ... -3.407396  -1.922010   
304 -2.397466      -1.110917       -2.641157  ... -3.375766  -1.868650   
305 -2.405462      -0.975889       -2.665854  ... -3.310175  -1.876855   
306 -2.321719      -0.965253       -3.408910  ... -3.275946  -2.161969   

     C20:4n-6, AA     C22:0  C20:5n-3, EPA  C22:4n-6      C24:0  C24:1n-9  \
0       -1.044779 -2.010884      -2.708831  -2.078207 -2.014278 -2.841654   
1       -1.138758 -2.086896      -2.105530  -2.316474 -2.059583 -2.833650   
2       -1.057313 -2.184049      -2.619077  -2.205983 -2.099682 -2.879920   
3       -1.188849 -2.062523      -2.106353  -2.439120 -2.045439 -2.703123   
4       -1.031387 -2.062978      -2.428238  -2.138552 -2.047075 -2.647746   
..            ...       ...            ...        ...       ...       ...   
302     -1.129934 -2.238050      -2.654091  -2.169548 -2.222853 -3.064523   
303     -1.060807 -2.165854      -2.241232  -2.124125 -2.186652 -2.632624   
304     -1.069915 -2.155608      -2.536164  -2.061249 -2.099950 -2.763178   
305     -1.065285 -2.027269      -2.256887  -2.173581 -1.959396 -2.495228   
306     -0.956042 -2.064162      -2.391672  -2.047897 -2.004234 -2.387483   

     C22:5n3, DPA  C22:6n3, DHA  
0       -2.574950     -1.986775  
1       -2.526006     -1.988272  
2       -2.717230     -2.060037  
3       -2.498506     -1.938969  
4       -2.542959     -1.909298  
..            ...           ...  
302     -2.551368     -1.934411  
303     -2.320090     -2.001102  
304     -2.434580     -2.045609  
305     -2.371536     -1.856706  
306     -2.418695     -1.792973  

[307 rows x 23 columns]

In [3]:
from hyperspy.signals import Signal1D

In [103]:
s = Signal1D(data_rpca)

In [115]:
s.decomposition(algorithm="RPCA", output_dimension=2)

Decomposition info:
  normalize_poissonian_noise=False
  algorithm=RPCA
  output_dimension=2
  centre=None


In [116]:
result_rpca=pd.DataFrame(s.learning_results.loadings, columns=['RPC1','RPC2'])

In [117]:
result_rpca

RPC1      RPC2
0    1.534217  0.027182
1   -1.349853 -0.143727
2   -1.834279 -0.223344
3    1.243019 -0.353796
4    0.561863 -0.042987
..        ...       ...
197  1.363003 -0.043771
198  7.035520 -0.261848
199  5.172401 -0.179883
200  1.807667 -0.057978
201 -1.646344 -0.179793

[202 rows x 2 columns]

In [111]:
s = Signal1D(data_rpca)

In [112]:
s.decomposition(algorithm="sklearn_pca",output_dimension=2)

Decomposition info:
  normalize_poissonian_noise=False
  algorithm=sklearn_pca
  output_dimension=2
  centre=None
scikit-learn estimator:
PCA(n_components=2)


In [113]:
result_pca=pd.DataFrame(s.learning_results.loadings, columns=['PC1','PC2'])

In [114]:
result_pca

PC1       PC2
0    1.594695  0.111057
1   -1.478702  0.911969
2   -1.571604 -1.538815
3    1.326547  0.434915
4    0.992239 -0.706801
..        ...       ...
197  2.115087 -0.446253
198  7.357246 -1.675874
199  5.900583  5.197955
200  1.839691 -0.004082
201 -1.360153  1.209694

[202 rows x 2 columns]

In [53]:
from sklearn.decomposition import PCA

In [67]:
pca = PCA(n_components=2)
pca.fit(data_rpca)

PCA(n_components=2)

In [68]:
pca.transform(data_rpca)

array([[ 1.59469472e+00,  1.11056663e-01],
       [-1.47870159e+00,  9.11969410e-01],
       [-1.57160399e+00, -1.53881514e+00],
       [ 1.32654668e+00,  4.34914995e-01],
       [ 9.92238830e-01, -7.06801464e-01],
       [ 1.29982104e+00,  3.78849977e-01],
       [ 1.54561740e+00, -1.11717477e+00],
       [-1.16583138e+00,  5.04008943e-01],
       [-6.66622392e-01,  9.51263226e-01],
       [ 4.68535125e-01,  1.56515292e+00],
       [ 1.36071980e+00,  1.47085351e+00],
       [ 1.76241000e+00,  5.07202127e-01],
       [ 3.49844876e+00, -3.50497172e-01],
       [ 1.41226998e+00,  5.47776445e-02],
       [-1.04509725e+00,  7.45182590e-01],
       [-2.42259278e-01, -5.43787681e-01],
       [ 7.48637398e-01, -1.10597917e+00],
       [-8.95510307e-01,  1.43142298e+00],
       [ 1.06771779e+00,  2.81199107e-01],
       [ 5.02442069e+00, -3.53538902e-01],
       [ 1.25937879e+00,  9.54428528e-02],
       [ 5.46970118e+00, -3.28954323e-01],
       [ 9.09561160e-01, -1.02523642e-02],
       [-3.

In [69]:
pca.explained_variance_ratio_

array([0.62950729, 0.05372699])

In [168]:
from sklearn.cluster import KMeans
from sklearn.mixture import GaussianMixture

In [171]:
kmeans = KMeans(n_clusters=3, random_state=0).fit(result_rpca)
kmeans.labels_

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 1, 2, 1,
       2, 0, 0, 2, 0, 0, 0, 2, 0, 0, 2, 2, 0, 2, 1, 1, 0, 0, 2, 2, 0, 0,
       0, 2, 2, 2, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 0, 0, 0, 1, 2,
       1, 2, 1, 2, 1, 1, 1, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 0, 2, 2, 2, 2,
       1, 2, 1, 1, 2, 1, 2, 2, 2, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 1, 2,
       0, 1, 0, 1, 1, 2, 2, 1, 1, 2, 2, 0, 2, 2, 0, 0, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 0, 2, 2, 2, 0, 2, 2, 2, 0, 1, 0, 2, 1, 2, 2, 1, 1,
       2, 2, 2, 1, 2, 2, 1, 1, 1, 1, 1, 1, 1, 2, 1, 2, 1, 2, 2, 1, 2, 2,
       1, 1, 2, 2])

In [176]:
kmeans.inertia_

883.2512977399902

In [188]:
kmeans.cluster_centers_

array([[-5.37931066, -0.15322181, -0.18440576],
       [ 4.82181036, -0.292003  , -0.26207779],
       [ 0.06621111, -0.1009687 ,  0.0645421 ]])

In [175]:
gm = GaussianMixture(n_components=3, random_state=0).fit(result_rpca)
gm.predict(result_rpca)

array([1, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 2, 1, 0, 1, 1, 1, 1, 1, 2, 0, 0,
       1, 2, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 2, 2, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 2, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 2, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 2, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 2, 2,
       1, 2, 1, 0], dtype=int64)

In [189]:
gm.means_

array([[-4.8523654 , -0.12531855, -0.24831458],
       [ 1.61491379, -0.42567366, -0.40413011],
       [ 0.86790295,  0.56475762,  1.10195609]])

In [12]:
pip install hyperspy[all]

     ---------------------------------------- 32.4/32.4 MB 2.3 MB/s eta 0:00:00
     -------------------------------------- 298.0/298.0 kB 3.7 MB/s eta 0:00:00
     -------------------------------------- 209.8/209.8 kB 2.5 MB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.


     ---------------------------------------- 95.8/95.8 kB 1.8 MB/s eta 0:00:00
     ---------------------------------------- 5.0/5.0 MB 3.1 MB/s eta 0:00:00
     -------------------------------------- 141.2/141.2 kB 2.8 MB/s eta 0:00:00
     ---------------------------------------- 1.1/1.1 MB 3.5 MB/s eta 0:00:00
     ---------------------------------------- 77.8/77.8 kB 2.2 MB/s eta 0:00:00
     -------------------------------------- 185.8/185.8 kB 3.7 MB/s eta 0:00:00
     -------------------------------------- 178.9/178.9 kB 3.6 MB/s eta 0:00:00
     ---------------------------------------- 95.7/95.7 kB 5.3 MB/s eta 0:00:00
     ---------------------------------------- 41.5/41.5 kB 2.0 MB/s eta 0:00:00
     ---------------------------------------- 1.8/1.8 MB 2.1 MB/s eta 0:00:00
     ---------------------------------------- 40.5/40.5 kB 1.9 MB/s eta 0:00:00
     ---------------------------------------- 14.1/14.1 MB 2.6 MB/s eta 0:00:00
     ----------------------------------------